name: 'Build & Push Docker Image'

on:
  schedule:
    - cron: "0 0 * * 0" # প্রতি রবিবার
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # GHCR এ পুশ করার জন্য আবশ্যিক

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build --tag mdarif76769/evil-phisher:latest .
          docker tag mdarif76769/evil-phisher:latest ghcr.io/mdarif76769/evil-phisher:latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images
        run: |
          docker push mdarif76769/evil-phisher:latest
          docker push ghcr.io/mdarif76769/evil-phisher:latest
