name: 'Build & Push Docker Image'

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          # আপনার চাওয়া অনুযায়ী 'Evil-Phisher' নাম দিয়ে বিল্ড
          docker build --tag mdarif76769/Evil-Phisher:latest .
          
          # GHCR এর জন্যও একই নাম ট্যাগ করা হলো
          docker tag mdarif76769/Evil-Phisher:latest ghcr.io/mdarif76769/Evil-Phisher:latest

      - name: Login to GHCR
        if: github.repository == 'mdarif76769/Evil-Phisher' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: github.repository == 'mdarif76769/Evil-Phisher' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images
        if: github.repository == 'mdarif76769/Evil-Phisher' && github.ref == 'refs/heads/main'
        run: |
          # DockerHub এ পুশ
          docker push mdarif76769/Evil-Phisher:latest
          
          # GHCR এ পুশ
          docker push ghcr.io/mdarif76769/Evil-Phisher:latest
